### PR TITLE
Update rebar in skel dir to 2.6.0

### PR DESCRIPTION
**Pull request by drobakowski**
The old one will cause compilation errors for new CB projects based on master.

### CODE REVIEW

**Comment by danikp** [comment]
What kind of errors?

**Comment by drobakowski** [comment]
With Erlang/OTP 18.0 & rebar 2.5.1:
```bash
> make
./rebar get-deps
...
==> my_project_name (get-deps)
./rebar compile
==> goldrush (pre_compile)
==> goldrush (compile)
ERROR: /private/tmp/my_project_name/deps/goldrush/.rebar/erlcinfo file version is incompatible. expected: 1 got: 2
ERROR: compile failed while processing /private/tmp/my_project_name/deps/goldrush: rebar_abort
make: *** [compile] Error 1
```

**Comment by danikp** [comment]
I had same problems after updating to 2.6.0
so this issue need some additional investigation.

**Comment by drobakowski** [comment]
@danikp hmm that's weird as I can't reproduce it with my env. The rebar version I've used for this is a copy of yours from the CB root. Can you reproduce this error for example with the sample project I've shared with https://github.com/ChicagoBoss/ChicagoBoss/issues/594#issuecomment-133649253? I've used the same env as in #594.

**Comment by danikp** [comment]
I got same problem here
https://travis-ci.org/danikp/erlang_iso8601/builds/75153391 and here
https://travis-ci.org/danikp/erlang_iso8601/builds/74874015

And in few other projects. rebar binary working on my system, but produce errors on Travis

**Comment by danikp** [comment]
I can propose to run 'make rebar_src' as part of 'make all'. It will download and compile rebar with version specified in Makefile prior to running anything else.

**Comment by drobakowski** [comment]
I'm not sure if the `make rebar_src` will fix the problem as this looks like a platform specific bug to me. Maybe we should create a ticket in the rebar project directly and see what this turns out.

**Comment by danikp** [comment]
superseded by #620
